spring:
  application:
    name: in4

  config:
    import: "optional:classpath:application-secret.yaml"

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        timeout: 120s # 초기화 타임 아웃 설정(프론트와 동일한 120초 설정)
      chat:
        model: llama3.2:3b
        options:
          temperature: 0.3
          keep-alive: 60m # 메모리를 1시간 동안 유지(만약 1시간 동안 대답이 없으면 메모리 해제)
    openai:
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3

server:
  port: 8888

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true